num_clients: 100
top_sites_file: "data/majestic_million.csv"
sites_to_load: 10000
client_request_rate: 0.001 # requests per second
ham_bandwidth: 10000.0
ham_retransmit_delay: 1.0
max_cache: 100
tx_error: 0.0
rx_error: 0.0
one_way_latency: 1.0
round_length:  100.0
cache_latency: 0.0

